# Generated by Django 4.1 on 2023-02-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0074_auto_20211117_1939"),
        ("user", "0091_action_is_removed"),
    ]

    operations = []
