# Generated by Django 4.1 on 2023-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0091_action_is_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reference_manager_onboarding_complete",
            field=models.BooleanField(default=False),
        ),
    ]
