# Generated by Django 4.1 on 2023-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0021_documenthub_hubmetadata_created_date_and_more"),
        ("researchhub_document", "0052_researchhubpost_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchhubunifieddocument",
            name="hubs_v2",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                through="hub.DocumentHub",
                to="hub.hubv2",
            ),
        ),
    ]
