# Generated by Django 4.1 on 2023-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0021_externalauthorclaimcase_target_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalauthorclaimcase",
            name="token_generated_time",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Intentionally setting as a int field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalauthorclaimcase",
            name="validation_attempt_count",
            field=models.IntegerField(
                default=-1,
                help_text="Number of attempts to validate themselves given token",
            ),
        ),
        migrations.AddField(
            model_name="externalauthorclaimcase",
            name="validation_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="authorclaimcase",
            name="validation_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
