# Generated by Django 4.1 on 2023-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_case",
            "0022_externalauthorclaimcase_token_generated_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="externalauthorclaimcase",
            name="provided_email",
            field=models.EmailField(
                default="noreply@researchhub.com",
                help_text="Requestors may use this field to validate themselves with this email",
                max_length=254,
            ),
            preserve_default=False,
        ),
    ]
