# Generated by Django 2.2 on 2021-12-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=128)),
                ('uid', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
