# Generated by Django 2.2 on 2022-01-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupyter', '0003_auto_20211217_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupytersession',
            name='token',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jupytersession',
            name='uid',
            field=models.CharField(max_length=128),
        ),
    ]
