# Generated by Django 4.1 on 2023-05-04 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_access_group", "0012_alter_permission_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="user",
        ),
        migrations.AddField(
            model_name="permission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Overriding AbstractGenericRelation created_by to be nullable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user to update the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="content_type",
            field=models.ForeignKey(
                help_text="Overriding AbstractGenericRelation related_name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_permission",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="updated_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
