# Generated by Django 2.2 on 2021-04-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0078_merge_20210311_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='extractor_type',
            field=models.CharField(choices=[('CERMINE', 'CERMINE'), ('ENGRAFO', 'ENGRAFO')], default=None, max_length=16, null=True),
        ),
    ]
