# Generated by Django 4.1 on 2023-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0113_papersubmission_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="is_removed_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
